CROP_DATABASE = {
    "tomatoes": {
        "name": "Tomatoes",
        "base_temp": 8.5,
        "upper_temp": 30.5,
        "gdd_required": 1500,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 27,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 500,
        "drought_resistance": "sensitive",
        "germination_temp_min": 10,
        "germination_temp_optimal": 25,
        "germination_temp_max": 35,
        # Yield data in kg per square meter
        "yield_kg_m2_lower": 3.0,
        "yield_kg_m2_average": 5.0,
        "yield_kg_m2_upper": 8.0,
        "sources": {
            "water": "FAO Land & Water - Tomato crop information",
            "germination": "UC Davis, J.F. Harrington - Vegetable Seed Germination",
            "drought": "Agronomy 2019, 9(8):447 - Physiological Responses of Vegetable Crops to Water Stress",
            "yield": "FAO Land & Water (45-65 tons/ha commercial); MSU Extension; La Ferme de Sainte Marthe"
        }
    },
    "lettuce": {
        "name": "Lettuce",
        "base_temp": 4,
        "upper_temp": 28,
        "gdd_required": 600,
        "min_sun_hours": 4,
        "optimal_temp_min": 7,
        "optimal_temp_max": 24,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 250,
        "drought_resistance": "moderate",
        "germination_temp_min": 2,
        "germination_temp_optimal": 20,
        "germination_temp_max": 27,
        "yield_kg_m2_lower": 1.5,
        "yield_kg_m2_average": 2.5,
        "yield_kg_m2_upper": 4.0,
        "sources": {
            "water": "FAO Irrigation and Drainage Paper 56",
            "germination": "UC Davis, J.F. Harrington - Vegetable Seed Germination",
            "drought": "Estimated from crop coefficients",
            "yield": "MSU Extension Table 4 (40 lb/100 sq ft); La Ferme de Sainte Marthe (3-6 kg/m²)"
        }
    },
    "spinach": {
        "name": "Spinach",
        "base_temp": 4.2,
        "upper_temp": 24.5,
        "gdd_required": 500,
        "min_sun_hours": 3,
        "optimal_temp_min": 10,
        "optimal_temp_max": 21,
        "frost_tolerance": "very_hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 200,
        "drought_resistance": "moderate",
        "germination_temp_min": 2,
        "germination_temp_optimal": 18,
        "germination_temp_max": 30,
        "yield_kg_m2_lower": 1.0,
        "yield_kg_m2_average": 2.0,
        "yield_kg_m2_upper": 3.0,
        "sources": {
            "water": "FAO Irrigation and Drainage Paper 56",
            "germination": "UC Davis - Vegetable Seed Germination",
            "drought": "Estimated from crop type",
            "yield": "MSU Extension Table 4 (40 lb/100 sq ft)"
        }
    },
    "peppers": {
        "name": "Peppers",
        "base_temp": 10,
        "upper_temp": 34.5,
        "gdd_required": 1400,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 29,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 600,
        "drought_resistance": "moderate",
        "germination_temp_min": 16,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 2.0,
        "yield_kg_m2_average": 3.0,
        "yield_kg_m2_upper": 5.0,
        "sources": {
            "water": "FAO Irrigation and Drainage Paper 56",
            "germination": "UC Davis, J.F. Harrington",
            "drought": "Estimated from solanaceae family characteristics",
            "yield": "MSU Extension Table 4 (48 lb/100 sq ft); University Extension data"
        }
    },
    "carrots": {
        "name": "Carrots",
        "base_temp": 5,
        "upper_temp": 29,
        "gdd_required": 800,
        "min_sun_hours": 4,
        "optimal_temp_min": 16,
        "optimal_temp_max": 21,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 350,
        "drought_resistance": "moderate",
        "germination_temp_min": 4,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 3.0,
        "yield_kg_m2_average": 5.0,
        "yield_kg_m2_upper": 8.0,
        "sources": {
            "water": "FAO Irrigation and Drainage Paper 56",
            "germination": "UC Davis - Vegetable Seed Germination",
            "drought": "Estimated from root crop characteristics",
            "yield": "MSU Extension Table 4 (69 lb/100 sq ft); La Ferme de Sainte Marthe (5-10 kg/m²)"
        }
    },
    "beans": {
        "name": "Beans",
        "base_temp": 9.5,
        "upper_temp": 32.5,
        "gdd_required": 900,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 27,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 300,
        "drought_resistance": "moderate_sensitive",
        "germination_temp_min": 16,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 1.5,
        "yield_kg_m2_average": 2.5,
        "yield_kg_m2_upper": 4.0,
        "sources": {
            "water": "FAO Irrigation and Drainage Paper 24",
            "germination": "UC Davis, J.F. Harrington",
            "drought": "Agronomy 2019, 9(8):447 - beans moderately sensitive to water stress",
            "yield": "MSU Extension Table 4 (34 lb/100 sq ft); La Ferme de Sainte Marthe (2-4 kg/m²)"
        }
    },
    "kale": {
        "name": "Kale",
        "base_temp": 4.2,
        "upper_temp": 27,
        "gdd_required": 700,
        "min_sun_hours": 4,
        "optimal_temp_min": 15,
        "optimal_temp_max": 23,
        "frost_tolerance": "very_hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 380,
        "drought_resistance": "moderate",
        "germination_temp_min": 4,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 2.0,
        "yield_kg_m2_average": 3.0,
        "yield_kg_m2_upper": 4.5,
        "sources": {
            "water": "FAO Paper 56 - Brassica group",
            "germination": "UC Davis - similar to cabbage",
            "drought": "Estimated from brassica family",
            "yield": "MSU Extension Table 4 (57 lb/100 sq ft)"
        }
    },
    "cucumbers": {
        "name": "Cucumbers",
        "base_temp": 10,
        "upper_temp": 35,
        "gdd_required": 1100,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 29,
        "frost_tolerance": "tender",
        "water_needs": "high",
        "season": "warm",
        "seasonal_water_mm": 500,
        "drought_resistance": "sensitive",
        "germination_temp_min": 16,
        "germination_temp_optimal": 30,
        "germination_temp_max": 40,
        "yield_kg_m2_lower": 2.0,
        "yield_kg_m2_average": 3.5,
        "yield_kg_m2_upper": 6.0,
        "sources": {
            "water": "FAO Irrigation and Drainage Paper 56",
            "germination": "UC Davis, J.F. Harrington",
            "drought": "Cucurbits generally drought sensitive",
            "yield": "MSU Extension Table 4 (50 lb/100 sq ft)"
        }
    },
    "radishes": {
        "name": "Radishes",
        "base_temp": 4,
        "upper_temp": 32.5,
        "gdd_required": 350,
        "min_sun_hours": 4,
        "optimal_temp_min": 10,
        "optimal_temp_max": 18,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 200,
        "drought_resistance": "moderate",
        "germination_temp_min": 4,
        "germination_temp_optimal": 27,
        "germination_temp_max": 32,
        "yield_kg_m2_lower": 0.3,
        "yield_kg_m2_average": 0.5,
        "yield_kg_m2_upper": 1.0,
        "sources": {
            "water": "FAO Paper 33 - short season vegetables",
            "germination": "UC Davis - Vegetable Seed Germination",
            "drought": "Root crops generally moderate tolerance",
            "yield": "MSU Extension Table 4 (11 lb/100 sq ft)"
        }
    },
    "arugula": {
        "name": "Arugula",
        "base_temp": 4,
        "upper_temp": 27,
        "gdd_required": 400,
        "min_sun_hours": 3,
        "optimal_temp_min": 10,
        "optimal_temp_max": 21,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 250,
        "drought_resistance": "moderate",
        "germination_temp_min": 4,
        "germination_temp_optimal": 20,
        "germination_temp_max": 30,
        "yield_kg_m2_lower": 1.0,
        "yield_kg_m2_average": 1.5,
        "yield_kg_m2_upper": 2.5,
        "sources": {
            "water": "Estimated from leafy greens group",
            "germination": "Similar to other brassicas",
            "drought": "Leafy greens moderate tolerance",
            "yield": "Estimated from similar leafy greens (lettuce, spinach)"
        }
    },
    "eggplant": {
        "name": "Eggplant",
        "base_temp": 10.5,
        "upper_temp": 35,
        "gdd_required": 1300,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 29,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 550,
        "drought_resistance": "moderate",
        "germination_temp_min": 16,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 3.0,
        "yield_kg_m2_average": 5.0,
        "yield_kg_m2_upper": 8.0,
        "sources": {
            "water": "FAO Paper 56 - Solanaceae",
            "germination": "UC Davis, J.F. Harrington",
            "drought": "Similar to tomato family",
            "yield": "MSU Extension Table 4 (46 lb/100 sq ft); La Ferme de Sainte Marthe (4-8 kg/m²); UVM Extension (16-24k lb/acre)"
        }
    },
    "broccoli": {
        "name": "Broccoli",
        "base_temp": 4.7,
        "upper_temp": 27,
        "gdd_required": 800,
        "min_sun_hours": 5,
        "optimal_temp_min": 15,
        "optimal_temp_max": 21,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 450,
        "drought_resistance": "moderate",
        "germination_temp_min": 4,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 0.5,
        "yield_kg_m2_average": 1.0,
        "yield_kg_m2_upper": 1.5,
        "sources": {
            "water": "FAO Paper 56 - Cole crops",
            "germination": "UC Davis - Vegetable Seed Germination",
            "drought": "Brassicas moderate tolerance",
            "yield": "MSU Extension Table 4 (16 lb/100 sq ft); Oklahoma State Extension (5 tons/acre)"
        }
    },
    "cabbage": {
        "name": "Cabbage",
        "base_temp": 4.2,
        "upper_temp": 27,
        "gdd_required": 900,
        "min_sun_hours": 5,
        "optimal_temp_min": 15,
        "optimal_temp_max": 21,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 450,
        "drought_resistance": "moderate",
        "germination_temp_min": 4,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 2.0,
        "yield_kg_m2_average": 3.5,
        "yield_kg_m2_upper": 6.0,
        "sources": {
            "water": "FAO Paper 56 Table 12",
            "germination": "UC Davis, J.F. Harrington",
            "drought": "Sustainability 2020, 12(10):3945",
            "yield": "MSU Extension Table 4 (48 lb/100 sq ft); Oklahoma State Extension (15 tons/acre)"
        }
    },
    "cauliflower": {
        "name": "Cauliflower",
        "base_temp": 4.2,
        "upper_temp": 30,
        "gdd_required": 850,
        "min_sun_hours": 5,
        "optimal_temp_min": 15,
        "optimal_temp_max": 21,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 450,
        "drought_resistance": "moderate",
        "germination_temp_min": 4,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 1.0,
        "yield_kg_m2_average": 1.8,
        "yield_kg_m2_upper": 3.0,
        "sources": {
            "water": "FAO Paper 56",
            "germination": "UC Davis",
            "drought": "Similar to cabbage",
            "yield": "MSU Extension Table 4 (33 lb/100 sq ft); Oklahoma State Extension (6.5 tons/acre)"
        }
    },
    "onions": {
        "name": "Onions",
        "base_temp": 3,
        "upper_temp": 35,
        "gdd_required": 1000,
        "min_sun_hours": 5,
        "optimal_temp_min": 13,
        "optimal_temp_max": 24,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 500,
        "drought_resistance": "moderate",
        "germination_temp_min": 2,
        "germination_temp_optimal": 24,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 3.0,
        "yield_kg_m2_average": 4.5,
        "yield_kg_m2_upper": 7.0,
        "sources": {
            "water": "FAO Paper 56 - bulb vegetables",
            "germination": "UC Davis",
            "drought": "Shallow roots, moderate tolerance",
            "yield": "MSU Extension Table 4 (92 lb/100 sq ft)"
        }
    },
    "garlic": {
        "name": "Garlic",
        "base_temp": 3,
        "upper_temp": 29,
        "gdd_required": 1200,
        "min_sun_hours": 5,
        "optimal_temp_min": 13,
        "optimal_temp_max": 24,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 450,
        "drought_resistance": "moderate",
        "germination_temp_min": 2,
        "germination_temp_optimal": 20,
        "germination_temp_max": 30,
        "yield_kg_m2_lower": 0.8,
        "yield_kg_m2_average": 1.2,
        "yield_kg_m2_upper": 2.0,
        "sources": {
            "water": "FAO Paper 56",
            "germination": "Similar to onions",
            "drought": "Similar to onions",
            "yield": "MSU Extension Table 4 (20 lb/100 sq ft); Grey Duck Garlic (4-10x multiplication factors)"
        }
    },
    "potato": {
        "name": "Potato",
        "base_temp": 3.5,
        "upper_temp": 30,
        "gdd_required": 1100,
        "min_sun_hours": 5,
        "optimal_temp_min": 15,
        "optimal_temp_max": 21,
        "frost_tolerance": "half_hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 500,
        "drought_resistance": "moderate",
        "germination_temp_min": 7,
        "germination_temp_optimal": 24,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 2.0,
        "yield_kg_m2_average": 3.5,
        "yield_kg_m2_upper": 5.0,
        "sources": {
            "water": "FAO Paper 56 Table 12",
            "germination": "UC Davis, J.F. Harrington",
            "drought": "Moderate sensitivity, critical during tuber initiation",
            "yield": "MSU Extension Table 4 (60 lb/100 sq ft); Hermie.com (4 kg/m²); Calculator Doc (2-4 kg/m²)"
        }
    },
    "sweet_potato": {
        "name": "Sweet Potato",
        "base_temp": 8,
        "upper_temp": 34,
        "gdd_required": 1400,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 29,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 600,
        "drought_resistance": "tolerant",
        "germination_temp_min": 16,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 1.5,
        "yield_kg_m2_average": 2.5,
        "yield_kg_m2_upper": 4.0,
        "sources": {
            "water": "FAO Paper 56",
            "germination": "UC Davis",
            "drought": "International Journal of AgriScience 2021 - orange fleshed sweet potato drought tolerance",
            "yield": "MSU Extension Table 4 (13 lb/100 sq ft - adjusted for intensive cultivation); Harvest to Table estimates"
        }
    },
    "squash": {
        "name": "Squash",
        "base_temp": 9,
        "upper_temp": 35,
        "gdd_required": 1000,
        "min_sun_hours": 6,
        "optimal_temp_min": 18,
        "optimal_temp_max": 27,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 450,
        "drought_resistance": "moderate",
        "germination_temp_min": 16,
        "germination_temp_optimal": 30,
        "germination_temp_max": 40,
        "yield_kg_m2_lower": 3.0,
        "yield_kg_m2_average": 5.0,
        "yield_kg_m2_upper": 8.0,
        "sources": {
            "water": "FAO Paper 56 - cucurbits",
            "germination": "UC Davis",
            "drought": "Cucurbits moderate sensitivity",
            "yield": "MSU Extension Table 4 (69 lb/100 sq ft summer squash); La Ferme de Sainte Marthe (4-7 kg/m² zucchini)"
        }
    },
    "pumpkin": {
        "name": "Pumpkin",
        "base_temp": 8.6,
        "upper_temp": 35,
        "gdd_required": 1100,
        "min_sun_hours": 6,
        "optimal_temp_min": 18,
        "optimal_temp_max": 27,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 500,
        "drought_resistance": "moderate",
        "germination_temp_min": 16,
        "germination_temp_optimal": 30,
        "germination_temp_max": 40,
        "yield_kg_m2_lower": 2.0,
        "yield_kg_m2_average": 3.5,
        "yield_kg_m2_upper": 6.0,
        "sources": {
            "water": "FAO Paper 56",
            "germination": "UC Davis",
            "drought": "Similar to squash",
            "yield": "MSU Extension Table 4 (60 lb/100 sq ft)"
        }
    },
    "melon": {
        "name": "Melon",
        "base_temp": 10,
        "upper_temp": 38,
        "gdd_required": 1200,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 29,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 400,
        "drought_resistance": "moderate",
        "germination_temp_min": 16,
        "germination_temp_optimal": 30,
        "germination_temp_max": 40,
        "yield_kg_m2_lower": 1.0,
        "yield_kg_m2_average": 2.0,
        "yield_kg_m2_upper": 3.5,
        "sources": {
            "water": "FAO Paper 56 - melon, cantaloupe",
            "germination": "UC Davis",
            "drought": "Cucurbits moderate",
            "yield": "MSU Extension Table 4 (28 lb/100 sq ft muskmelon)"
        }
    },
    "watermelon": {
        "name": "Watermelon",
        "base_temp": 11.35,
        "upper_temp": 37,
        "gdd_required": 1300,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 32,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 500,
        "drought_resistance": "moderate",
        "germination_temp_min": 16,
        "germination_temp_optimal": 32,
        "germination_temp_max": 40,
        "yield_kg_m2_lower": 1.5,
        "yield_kg_m2_average": 3.0,
        "yield_kg_m2_upper": 5.0,
        "sources": {
            "water": "FAO Paper 56",
            "germination": "UC Davis, J.F. Harrington",
            "drought": "Deep roots, moderate tolerance",
            "yield": "MSU Extension Table 4 (17 lb/100 sq ft - adjusted for large fruit size per area)"
        }
    },
    "strawberries": {
        "name": "Strawberries",
        "base_temp": 3,
        "upper_temp": 30,
        "gdd_required": 800,
        "min_sun_hours": 6,
        "optimal_temp_min": 15,
        "optimal_temp_max": 26,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 450,
        "drought_resistance": "sensitive",
        "germination_temp_min": 10,
        "germination_temp_optimal": 21,
        "germination_temp_max": 30,
        "yield_kg_m2_lower": 1.5,
        "yield_kg_m2_average": 3.0,
        "yield_kg_m2_upper": 5.0,
        "sources": {
            "water": "FAO Paper 56 - berries",
            "germination": "UC Davis",
            "drought": "Shallow-rooted, sensitive",
            "yield": "Hydroponic Systems EU case study (typical 4-6 kg/m², advanced systems up to 12.5 kg/m²); adjusted for conventional growing"
        }
    },
    "peas": {
        "name": "Peas",
        "base_temp": 4.75,
        "upper_temp": 27,
        "gdd_required": 700,
        "min_sun_hours": 5,
        "optimal_temp_min": 10,
        "optimal_temp_max": 21,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 350,
        "drought_resistance": "moderate_sensitive",
        "germination_temp_min": 4,
        "germination_temp_optimal": 24,
        "germination_temp_max": 30,
        "yield_kg_m2_lower": 0.8,
        "yield_kg_m2_average": 1.2,
        "yield_kg_m2_upper": 2.0,
        "sources": {
            "water": "FAO Paper 56 - legumes",
            "germination": "UC Davis",
            "drought": "Agronomy 2019 - peas moderately sensitive",
            "yield": "MSU Extension Table 4 (24 lb/100 sq ft shelled peas)"
        }
    },
    "corn": {
        "name": "Corn/Maize",
        "base_temp": 9,
        "upper_temp": 34.5,
        "gdd_required": 1400,
        "min_sun_hours": 6,
        "optimal_temp_min": 21,
        "optimal_temp_max": 32,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 550,
        "drought_resistance": "moderate_sensitive",
        "germination_temp_min": 10,
        "germination_temp_optimal": 30,
        "germination_temp_max": 40,
        "yield_kg_m2_lower": 0.4,
        "yield_kg_m2_average": 0.7,
        "yield_kg_m2_upper": 1.2,
        "sources": {
            "water": "FAO Paper 56 Table 12 - maize",
            "germination": "UC Davis, J.F. Harrington",
            "drought": "Agronomy 2019 - moderately sensitive, critical at tasseling",
            "yield": "USDA NASS (177 bu/acre avg = ~11 tons/ha); MSU Extension Table 4 (36 lb kernels/100 sq ft)"
        }
    },
    "basil": {
        "name": "Basil",
        "base_temp": 10.95,
        "upper_temp": 35,
        "gdd_required": 600,
        "min_sun_hours": 6,
        "optimal_temp_min": 18,
        "optimal_temp_max": 27,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 300,
        "drought_resistance": "moderate",
        "germination_temp_min": 18,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 0.5,
        "yield_kg_m2_average": 1.0,
        "yield_kg_m2_upper": 2.0,
        "sources": {
            "water": "Estimated from herb requirements",
            "germination": "UC Davis",
            "drought": "Aromatic herbs moderate tolerance",
            "yield": "ResearchGate study (0.71 kg per plant Sweet Genovese); Purdue Extension; estimated at 1-2 plants per sq ft"
        }
    },
    "parsley": {
        "name": "Parsley",
        "base_temp": 4,
        "upper_temp": 27,
        "gdd_required": 500,
        "min_sun_hours": 4,
        "optimal_temp_min": 10,
        "optimal_temp_max": 21,
        "frost_tolerance": "hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 300,
        "drought_resistance": "moderate",
        "germination_temp_min": 4,
        "germination_temp_optimal": 21,
        "germination_temp_max": 30,
        "yield_kg_m2_lower": 0.5,
        "yield_kg_m2_average": 1.0,
        "yield_kg_m2_upper": 1.8,
        "sources": {
            "water": "Estimated from herb crops",
            "germination": "UC Davis",
            "drought": "Moderate tolerance",
            "yield": "MSU Extension Table 4 (24 lb/100 sq ft); estimated for multiple cuttings"
        }
    },
    "wheat": {
        "name": "Wheat",
        "base_temp": 0,
        "upper_temp": 33,
        "gdd_required": 2000,
        "min_sun_hours": 5,
        "optimal_temp_min": 15,
        "optimal_temp_max": 24,
        "frost_tolerance": "very_hardy",
        "water_needs": "moderate",
        "season": "cool",
        "seasonal_water_mm": 550,
        "drought_resistance": "moderate_tolerant",
        "germination_temp_min": 4,
        "germination_temp_optimal": 24,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 0.3,
        "yield_kg_m2_average": 0.45,
        "yield_kg_m2_upper": 0.7,
        "sources": {
            "water": "FAO Paper 56 Table 12 - wheat",
            "germination": "UC Davis",
            "drought": "Frontiers Plant Science 2023 - some varieties drought tolerant",
            "yield": "Purdue/farmdoc (4.48 tons/ha average international); Our World in Data; USDA"
        }
    },
    "rice": {
        "name": "Rice",
        "base_temp": 10,
        "upper_temp": 38.5,
        "gdd_required": 2200,
        "min_sun_hours": 5,
        "optimal_temp_min": 21,
        "optimal_temp_max": 32,
        "frost_tolerance": "tender",
        "water_needs": "high",
        "season": "warm",
        "seasonal_water_mm": 1000,
        "drought_resistance": "sensitive",
        "germination_temp_min": 10,
        "germination_temp_optimal": 30,
        "germination_temp_max": 40,
        "yield_kg_m2_lower": 0.3,
        "yield_kg_m2_average": 0.5,
        "yield_kg_m2_upper": 0.8,
        "sources": {
            "water": "FAO Paper 56 Table 12 - paddy rice",
            "germination": "UC Davis",
            "drought": "Plant Cell Physiol. 2016 - most rice sensitive, breeding efforts ongoing",
            "yield": "USDA NASS (7,649 lb/acre = ~8.6 tons/ha); Our World in Data; FAO data (variable by region 3-10 tons/ha)"
        }
    },
    "soybeans": {
        "name": "Soybeans",
        "base_temp": 8.5,
        "upper_temp": 30,
        "gdd_required": 1500,
        "min_sun_hours": 5,
        "optimal_temp_min": 21,
        "optimal_temp_max": 29,
        "frost_tolerance": "tender",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 500,
        "drought_resistance": "moderate_sensitive",
        "germination_temp_min": 10,
        "germination_temp_optimal": 30,
        "germination_temp_max": 40,
        "yield_kg_m2_lower": 0.2,
        "yield_kg_m2_average": 0.35,
        "yield_kg_m2_upper": 0.5,
        "sources": {
            "water": "FAO Paper 56 - soybeans",
            "germination": "UC Davis",
            "drought": "Moderately sensitive to water stress",
            "yield": "USDA NASS (50.6 bu/acre = ~3.4 tons/ha); Our World in Data; Iowa State Extension"
        }
    },
    "sunflower": {
        "name": "Sunflower",
        "base_temp": 8,
        "upper_temp": 37.5,
        "gdd_required": 1200,
        "min_sun_hours": 6,
        "optimal_temp_min": 18,
        "optimal_temp_max": 27,
        "frost_tolerance": "half_hardy",
        "water_needs": "moderate",
        "season": "warm",
        "seasonal_water_mm": 500,
        "drought_resistance": "tolerant",
        "germination_temp_min": 7,
        "germination_temp_optimal": 27,
        "germination_temp_max": 35,
        "yield_kg_m2_lower": 0.15,
        "yield_kg_m2_average": 0.25,
        "yield_kg_m2_upper": 0.4,
        "sources": {
            "water": "FAO Paper 56 - sunflower",
            "germination": "UC Davis",
            "drought": "Deep rooting system, relatively drought tolerant",
            "yield": "USDA data (~1.5-3 tons/ha typical); Our World in Data; FAO Statistics"
        }
    }
}

# Note on yield variations:
# - Lower bounds represent yields in less optimal conditions, beginning gardeners, or marginal soils
# - Average yields represent good home garden or small-scale commercial production under normal conditions
# - Upper bounds represent optimal conditions, experienced growers, greenhouse/protected cultivation, or intensive methods
# - Commercial large-scale yields may differ from small-scale intensive garden yields
# - Greenhouse and hydroponic systems can achieve significantly higher yields than field production
# - Values are for fresh weight unless otherwise noted (grains are at standard moisture content)